image: debian:sid

stages:
    - check

shellcheck:
    stage: check
    before_script:
        - apt-get --assume-yes --quiet update >/dev/null 2>&1
        - apt-get --assume-yes --quiet install make shellcheck innoextract icoutils imagemagick wget >/dev/null 2>&1
    script:
        - ./tests/shellcheck-lib.sh
        - ./tests/shellcheck-main-script.sh
        - ./tests/shellcheck-game-scripts.sh
        - ./tests/shellcheck-launcher-script.sh
    artifacts:
        paths:
            - play.it-2/lib/libplayit2.sh
