#!/bin/sh
set -e

readonly SCRIPT="$1"

check_2_10() {
	# complete, no false positives
	grep --quiet "$SCRIPT" \
		--regexp '_DEB.*libudev1' \
		--regexp 'lib.*systemd' \
		&& echo use \'libudev1\' generic dependency
	grep --quiet '_DEPS.*libtheora' "$SCRIPT" \
		&& echo use \'theora\' generic dependency
	check_2_9
}

check_2_9() {
	check_2_8
}

check_2_8() {
	grep --quiet 'for path in' "$SCRIPT" \
		|| echo update PLAYIT_LIB2 search path
	check_2_7
}

check_2_7() {
	grep --quiet ARCHIVES_LIST "$SCRIPT" \
		&& echo ARCHIVES_LIST is usually automatically detected
}

version=$(grep target_version "$SCRIPT" | cut --delimiter "'" --fields 2 | tr . _)
check_"$version"
